version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_pedidos
    environment:
      MYSQL_DATABASE: testepedido
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_db_pedidos:/var/lib/mysql

volumes:
  mysql_db_pedidos:
